spring:
  redis:
    #deploymentMode单机时为single,集群时为cluster
    deploymentMode: single

    database: 0
    password:

    # 单机模式
    host: ${zetacloud.server.redis.default.ip}
    port: ${zetacloud.server.redis.default.port}

    # 集群模式
    #sentinel:  # sentinel cluster mode
    #  master: mymaster
    #  nodes: ${zetacloud.server.sentinel.default.nodes}
    clusterxx:   # offical cluster mode
      # 各 Redis 节点信息
      nodes: ${zetacloud.server.redis-cluster.default.nodes}
      # 执行命令超时时间
      command-timeout: 15000
      # 重试次数
      max-attempts: 5
      # 跨集群执行命令时要遵循的最大重定向数量
      max-redirects: 3
      # 连接池最大连接数（使用负值表示没有限制）
      max-active: 16
      # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-wait: -1
      # 连接池中的最大空闲连接
      max-idle: 8
      # 连接池中的最小空闲连接
      min-idle: 0
      # 是否在从池中取出连接前进行检验,如果检验失败,则从池中去除连接并尝试取出另一个
      test-on-borrow: true

    jedis:
      pool:
        max-idle: 8
        min-idle: 0
        max-active: 8
        max-wait: -1
        shutdown-timeout: 100ms
    ssl: false
    timeout: 20000
