# redisson config
spring:
  redis:
    redisson: 
      file: classpath:redisson.yaml
      config: |
        singleServerConfig:
          idleConnectionTimeout: 10000
          connectTimeout: 10000
          timeout: 3000
          retryAttempts: 3
          retryInterval: 1500
          password: null
          subscriptionsPerConnection: 5
          clientName: null
          address: "redis://devinfra1:6380"
          subscriptionConnectionMinimumIdleSize: 1
          subscriptionConnectionPoolSize: 50
          connectionMinimumIdleSize: 32
          connectionPoolSize: 64
          database: 0
          dnsMonitoringInterval: 5000
        threads: 0
        nettyThreads: 0
        codec: !<org.redisson.codec.JsonJacksonCodec> {}
        transportMode: "NIO"
#        clusterServersConfig:
#          idleConnectionTimeout: 10000
#          connectTimeout: 10000
#          timeout: 3000
#          retryAttempts: 3
#          retryInterval: 1500
#          failedSlaveReconnectionInterval: 3000
#          failedSlaveCheckInterval: 60000
#          password: null
#          subscriptionsPerConnection: 5
#          clientName: null
#          loadBalancer: !<org.redisson.connection.balancer.RoundRobinLoadBalancer> {}
#          subscriptionConnectionMinimumIdleSize: 1
#          subscriptionConnectionPoolSize: 50
#          slaveConnectionMinimumIdleSize: 24
#          slaveConnectionPoolSize: 64
#          masterConnectionMinimumIdleSize: 24
#          masterConnectionPoolSize: 64
#          readMode: "SLAVE"
#          subscriptionMode: "SLAVE"
#          nodeAddresses:
#          - "redis://10.10.102.78:6380"
#          - "redis://10.10.102.80:6380"
#          - "redis://10.10.102.82:6380"
#          scanInterval: 1000
#          pingConnectionInterval: 0
#          keepAlive: false
#          tcpNoDelay: false
#        threads: 16
#        nettyThreads: 32
#        codec: !<org.redisson.codec.MarshallingCodec> {}
#        transportMode: "NIO"