server:
  port: 8082

spring:
  application:
    name: eureka-provider

eureka:
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
    prefer-ip-address: true
    instance-id: ${random.uuid}:${spring.application.name}:${server.port}
  client:
    service-url:
      defaultZone: http://admin:admin@localhost:8080/eureka/