server:
  port: 7001

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri:
          username:
          password:
  rabbitmq:
    host: 192.168.31.129
    port: 5672
    username: admin
    password: admin
eureka:
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
    prefer-ip-address: true
    instance-id: ${random.uuid}:${spring.application.name}:${server.port}
  client:
    service-url:
      defaultZone: http://admin:admin@localhost:8080/eureka/
