
spring:
  config:
    name: rabbitmq-provider
  rabbitmq:
    host: 192.168.31.129
    port: 5672
    username: admin
    password: admin
    publisher-confirms: true
    publisher-returns: true
    template:
      mandatory: true
    listener:
      simple:
        acknowledge-mode: manual # 消费者消息确认模式，可选值：none, manual, auto
        retry:
          enabled: false
          initial-interval: 2000
          max-attempts: 5
          multiplier: 1.0
server:
  port: 8084
